#pragma config(Sensor, S2,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S3,     lightSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Robot name: Gary
/* Team members: Gajun, Sarah, Suryanash, Tom*/

int const RED = 5;

/* int motB, motC: power of motors
 * Gary will move until it touches a wall at a given motor power
 */
void moveTillTouch(int motB, int motC)
{
	while(SensorValue(touchSensor) == 0){
		motor[motorB] = motB;
		motor[motorC] = motC;
	}

}

/* int distance: distance between robot and wall
 * int motB, motC: motor POWER
 * Gary will move backwards at a given distance based on sonarSensor
 */
void backupFromWall(int distance, int motB, int motC)
{
	while(SensorValue(sonarSensor) < distance){
		motor[motorB] = motB;
		motor[motorC] = motC;
	}
}

/* int motB, motC: motor POWER
 * int time: time of rotation
 * Turning at a certain angle
 */
void turn(int motB, int motC, int time)
{
	motor[motorB] = motB;
	motor[motorC] = motC;
	wait1Msec(time);
}

/*int color: integer number for a specific color
 *int motB, motC: motor power
 *Gary moves in a straight line until it finds the color red
 */
void searchColorLine(int color, int motB, int motC)
{
	while(SensorValue(lightSensor) != color){
		motor[motorB] = motB;
		motor[motorC] = motC;
	}
}

/*int color: integer number for a specific color
 *int strong, weak: power of motors
 *int degree: degree of rotation on wheels
 *Gary will travel along the line while bouncing left and right
 */
void travelOnLine(int color, int strong, int weak, int degree)
{
	//reset rotation count
	nMotorEncoder[motorB] = 0;
	nMotorEncoder[motorC] = 0;

	while(nMotorEncoder[motorB] < degree && nMotorEncoder[motorC] < degree)
	{
		if(SensorValue(lightSensor) == color){
			motor[motorB] = strong;
			motor[motorC] = weak;
		}
		else{
			motor[motorB] = weak;
			motor[motorC] = strong;
		}
 	}
}

/* int distance: distance between robot and wall
 * int motB, motC: motor POWER
 * Gary will move up to a given distance from the wall based on the sonar sensor
 */
void MoveUpToWall(int distance, int motB, int motC)
{
	while(SensorValue(sonarSensor) > distance){
		motor[motorB] = motB;
		motor[motorC] = motC;
	}
}

/*
 *int motB, motC: motor POWER
 *int degree: the rotation
 *The number of rotations on the wheel
 */
void rotation(int motB, int motC, int degree){
	nMotorEncoder[motorB] = 0;
	nMotorEncoder[motorC] = 0;

	while(nMotorEncoder[motorB] < degree && nMotorEncoder[motorC] < degree)
	{
			motor[motorB] = motB;
			motor[motorC] = motC;
}
}
task main()
{
	//Part 1 Move to wall and move back
	moveTillTouch(60,60);
	backupFromWall(10,-20,-20);

	//turn move back and move through red line
	turn(-17,17, 1250);
	searchColorLine(RED, 20, 20);
	travelOnLine(RED,30,10,2400);

	//Move to calibration area
	MoveUpToWall(5,20,20);
	turn(17,-17,1000);
	MoveUpToWall(7,20,20);

	//Move out of calibration area and hit the box
	turn(17,-17,2000);
	MoveUpToWall(9,40,40);
	turn(-17,17,975);
	MoveUpToWall(19,40,40);

	//turn and move to the finished area
	turn(-17,17,650);
	rotation(30,30,1650);

	//flourish
	turn(50,-50,2000);

}
